dupc/dupc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainsite.urls',namespace='mainsite')),
    path('account/',include('account.urls',namespace='account')),
    
    path('publication/',include('publication.urls',namespace='publication')),
    path('news_and_updates/',include('news.urls',namespace = 'news')),
    path('outreach/',include('outreach.urls',namespace = 'outreach')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('stories/',include('stories.urls',namespace='stories')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/accounts/login/',views.loginn,name = 'login')
]+  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

dupc/publication/urls.py
from .import views
from django.contrib import admin
from django.urls import path

app_name = 'publication'

urlpatterns = [
	path('',views.publicationss,name='publication'),
	path('add/',views.addpublication,name='add'),
]

dupc/reports/urls.py
from django.conf.urls import url, include
from .import views
from django.contrib import admin
from django.urls import path

app_name = 'reports'

urlpatterns = [
    path('',views.reports,name = 'reports'),
    path('add/',views.add,name = 'add'),
]

dupc/stories/urls.py
from .import views
from django.contrib import admin
from django.urls import path
app_name = 'stories'

urlpatterns = [

    path('',views.stories,name = 'stories'),
    path('add/',views.add,name = 'add'),
] 

dupc/publication/models.py
from django.db import models

# Create your models here.
class publication(models.Model):
	authors = models.CharField(max_length=1200)
	title = models.CharField(max_length=1000)
	name = models.CharField(max_length=700)
	pdf = models.FileField(upload_to='files/',blank=True)
	link = models.CharField(max_length=500,blank=True)
	has_pdf = models.BooleanField(default=False)
	body = models.TextField(max_length=5000,default=False)
	
	def __str__(self):
		return self.title

dupc/publication/views.py
from django.shortcuts import render, get_object_or_404,redirect	
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.utils.datastructures import MultiValueDictKeyError
from .models import *

# Create your views here.
def publicationss(request):
	Publication = publication.objects.filter().order_by('-id')
	return render(request, 'publication/publication.html',{'Publication':Publication})

@login_required(login_url = "/account")
def addpublication(request):
	if request.method == 'POST':
		if request.POST['author'] and request.POST['title'] and request.POST['name'] and request.POST['url'] and request.POST['body']:
			pub = publication()
			if request.POST['gridRadios'] == "1":
				try:
					fm = request.FILES['fl']
				except MultiValueDictKeyError:
					return render(request,'publication/create.html',{'error_message':'Select File Or Change Option'})
				
				pub.pdf = request.FILES['fl']
				pub.has_pdf = True
			else:
				pub.has_pdf = False
			

			pub.authors = request.POST['author']
			pub.title = request.POST['title']
			pub.name = request.POST['name']
			pub.body = request.POST['body']
			pub.link = request.POST['url']
			pub.save()
			return redirect('publication:publication')
		else:
			return render(request,'publication/create.html',{'error_message':'All Field Required'})
	else:
		return render(request,'publication/create.html')

dupc/publication/templates/publication/create.html
{% extends 'base.html' %}

{% block ccd %}
      <br>
      <b><h3 style="padding-left: 13%;">Add Publications</h3></b>
    
    <div class = "container" >
    <br>
    {% if error_message %}
      
<div class="alert alert-danger" >
  <strong>Warning!</strong> {{error_message}}
</div>
    {% endif %}
    </div>

<form method = 'POST' action = "#" enctype = "multipart/form-data">
    {% csrf_token %}
    <br><br>
    <div class = "container">
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="author">Authors</label>
      <textarea class="form-control" name = "author" id = "author" rows="1" placeholder ="Enter Authers followed by,"></textarea>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="title">Title</label>
      <textarea class="form-control" name = "title" id = "title" rows="1" placeholder ="Title of Publication"></textarea>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="body">Enter Detail</label>
      <textarea class="form-control" name = "body" id = "body" rows="3" placeholder ="Enter Detail about Publication"></textarea>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name = "name" placeholder=" Book/Journal Name">
    </div>
    </div>
  <div class="form-row">
    <div class="form-group col-md-12">
      <label for="url">Url</label>
      <input type="text" class="form-control" id="url" name = "url" placeholder="insert URL">
    </div>
	</div>
	
     <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Have File</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="1" checked>
          <label class="form-check-label" for="gridRadios1">
            Yes
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="0">
          <label class="form-check-label" for="gridRadios2">
            No
          </label>
        </div>
        
      </div>
    </div>
  </fieldset><br>
   
    
  <div class="form-group">
      <label for="fl">Upload File</label>
    <input type = "file" class = "form-control-file" name = "fl" id = "fl">
  </div><br>
 
  <button type="submit" class="btn btn-primary">Add</button>
</form>
</div>
<br><br>

{% endblock ccd %}

dupc/publication/templates/publication/publication.html
{% extends 'base.html' %}

{% block ccd %}

  
<div id="marine-content-inner"> 
    
    <!-- Main Content -->
    
  <section id="main-content"> 
      
      <!-- Container -->
      <br><br>
      <div class="container">
          <div class="row justify-content-start" style="font-size: 120%; font-family: Raleway;">
            	<div class="col-lg-3 col-md-3 col-sm-3">
              		<p style="color: #000; border-left: 2px solid #169EB7; padding-left: 15px;">
                	<a href="{%url 'publication:publication' %}" style="color: #000;">Publications</a><br><br>
                	<a href="{%url 'reports:reports'%}" style="color: #000;">Reports</a><br><br>
                	<a href="{%url 'stories:stories'%}" style="color: #000;">Multimedia Stories</a>
              		</p>
            	</div>

            	<div class="col-lg-7 col-md-7 col-sm-7">
              		<div class="page-heading">
                		<h2 style="color: #169EB7; font-weight: 400;font-family: Raleway;">Publications</h2><br>
            		  </div>
                  <div class = "row justify-content-between">
                  {%for pub in Publication.all%}
                  <div class = "col-12" style = "border-style:solid;">

                  <br><h4 style="color: #169EB7; font-weight: 400;">{{pub.title}}</h4>
                  <p style="font-family: 'Raleway'; font-size:100%;text-align:justify;">{{pub.name}}<br><br><span style = "color:#169EB7;"><b>{{pub.authors}}</b><br></span>{{pub.body}}<br><br><span style = "color:#169EB7;"><a href = "{{pub.link}}" target = "_blank" style  = "color:#169EB7; text-decoration: none;"><b>Know More</b></a></span><br>{%if pub.has_pdf == True%}<span style ="color:#169EB7;" ><a href = "{{pub.pdf.url}}" target = "_blank" style = "color:#169EB7; text-decoration: none;"><b>View Publication</b></a></span>{%endif%}</p><br><br>
                  </div>&emsp;
                  {%endfor%}
                  </div>




                </div>
          </div>
        </div>
	  </section>
</div>

<div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
          <br>
            {% if user.is_authenticated %}
          <h4 class="breadcrumbs" align = "center"><span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'publication:add'%}" role="button">Add Publication</a></span></h4>
            {%endif%}
        </div>
      </div>
        
        
</div>

<br>
{%endblock%}

<!-- /Marine Content Wrapper --> 

<!-- JavaScript --> 

<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/SmoothScroll.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.prettyPhoto.js"></script> 
<script type="text/javascript" src="assets/js/modernizr.js"></script> 
<script type="text/javascript" src="assets/js/wow.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.sharre.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.flexslider-min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.knob.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script> 
<script type="text/javascript" src="assets/js/masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.fitvids.js"></script> 
<script type="text/javascript" src="assets/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.nouislider.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.validity.min.js"></script> 
<script type="text/javascript" src="assets/js/tweetie.min.js"></script> 
<script type="text/javascript" src="assets/js/script.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.enablelog.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.tools.min.js"></script> 
<script type="text/javascript">



jQuery(document).ready(function() {



    jQuery('.tp-banner').show().revolution(



    {



        dottedOverlay:"none",



        delay:16000,



        startwidth:1170,



        startheight:700,



        hideThumbs:200,



        thumbWidth:100,



        thumbHeight:50,



        thumbAmount:5,



        navigationType:"bullet",



        navigationArrows:"solo",



        navigationStyle:"preview2",



        touchenabled:"on",



        onHoverStop:"on",



        swipe_velocity: 0.7,



        swipe_min_touches: 1,



        swipe_max_touches: 1,



        drag_block_vertical: false,



                                parallax:"mouse",



        parallaxBgFreeze:"on",



        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],



        keyboardNavigation:"off",



        navigationHAlign:"center",



        navigationVAlign:"bottom",



        navigationHOffset:0,



        navigationVOffset:20,



        soloArrowLeftHalign:"left",



        soloArrowLeftValign:"center",



        soloArrowLeftHOffset:20,



        soloArrowLeftVOffset:0,



        soloArrowRightHalign:"right",



        soloArrowRightValign:"center",



        soloArrowRightHOffset:20,



        soloArrowRightVOffset:0,



        shadow:0,



        fullWidth:"on",



        fullScreen:"off",



        spinner:"spinner4",



        stopLoop:"off",



        stopAfterLoops:-1,



        stopAtSlide:-1,



        shuffle:"off",



        autoHeight:"off",                       



        forceFullWidth:"off",                       



        hideThumbsOnMobile:"off",



        hideNavDelayOnMobile:1500,                      



        hideBulletsOnMobile:"off",



        hideArrowsOnMobile:"off",



        hideThumbsUnderResolution:0,



        hideSliderAtLimit:0,



        hideCaptionAtLimit:0,



        hideAllCaptionAtLilmit:0,



        startWithSlide:0,



        videoJsPath:"rs-plugin/videojs/",



        fullScreenOffsetContainer: ""   



    });



}); //ready



</script> 



<script src="assets/js/readmore.js"></script>

<script>
$('#info').readmore({
  moreLink: '<a href="#">Usage, examples, and options</a>',
  collapsedHeight: 384,
  afterToggle: function(trigger, element, expanded) {
    if(! expanded) { // The "Close" link was clicked
      $('html, body').animate({scrollTop: element.offset().top}, {duration: 100});
    }
  }
});

$('article').readmore({speed: 500});
</script>

<!-- Mirrored from marine.arenaofthemes.com/index-creative-light.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2015 21:07:18 GMT -->