dupc/dupc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainsite.urls',namespace='mainsite')),
    path('account/',include('account.urls',namespace='account')),
    
    path('publication/',include('publication.urls',namespace='publication')),
    path('news_and_updates/',include('news.urls',namespace = 'news')),
    path('outreach/',include('outreach.urls',namespace = 'outreach')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('stories/',include('stories.urls',namespace='stories')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/accounts/login/',views.loginn,name = 'login')
]+  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

dupc/news/urls.py
from django.conf.urls import url, include
from .import views
from django.contrib import admin
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('',views.newss,name = 'news'),
    path('<int:year>/<str:month>/',views.nss,name = 'nss'),
    path('add/',views.addnews,name = 'add'),
    path('addupdate/',views.addupdate,name = 'addupdate'),
    path('<int:pk_id>/', views.detail, name = 'detail'),
]

dupc/news/models.py
from django.db import models


class news(models.Model):
    title = models.CharField(max_length=500)
    body = models.TextField(max_length = 3000 ,default= None)
    url = models.CharField(max_length=500)
    date = models.IntegerField(default=12)
    month = models.CharField(max_length=50,default="june")
    year = models.IntegerField(default=2020)
    file = models.FileField(upload_to ='files/')
    has_url = models.BooleanField(default = True)
    has_file = models.BooleanField(default = True)

    def summary(self):
        return self.body[:250]
        
    def __str__(self):
        return self.title


class update(models.Model):
    title = models.CharField(max_length=500)
    body = models.TextField(max_length = 3000 ,default= None)
    url = models.CharField(max_length=500,blank = True)
    date = models.IntegerField(default=12)
    month = models.CharField(max_length=50,default="june")
    year = models.IntegerField(default=2020)
    file = models.FileField(upload_to ='files/')
    image = models.ImageField(upload_to = 'images/',blank  = True)
    has_url = models.BooleanField(default = True)
    has_file = models.BooleanField(default = True)
    has_image = models.BooleanField(default = False)

    def __str__(self):
        return self.title

    def recent(self):
        return update.objects.all()[:5]
    

dupc/news/views.py
from django.shortcuts import render
from .models import news,update
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

from django.utils.datastructures import MultiValueDictKeyError

# Create your views here.
def newss(request):
   
    up = update.objects.filter().order_by('-id')
    
    return render(request,'news/news.html',{'up':up})


def nss(request,year,month):
   
    Ns = news.objects.filter(year = year)
    News = Ns.filter(month = month)
    
    return render(request,'news/news_display.html',{'News':News})




@login_required(login_url = "/account")
def addnews(request):
    if request.method == 'POST':
        
        
        if request.POST['title'] and request.POST['detail'] and request.POST['date'] and request.POST['month'] and  request.POST['year']:
            ns = news()
            if request.POST['gridRadios1'] == "1" and request.POST['url']:
                ns.url = request.POST['url']
                ns.has_url = True
            elif request.POST['gridRadios1'] == "1":
                return render(request, 'news/create.html',{'error_message':'Url required. or Change Has Url Option'})
            else:
                ns.has_url = False

            if request.POST['gridRadios'] == "1":
                try:
                    fm = request.FILES['fl']
                except MultiValueDictKeyError:
                    return render(request, 'news/create.html',{'error_message':'File required. or Change Has File Option'})
                ns.file = request.FILES['fl']
                ns.has_file = True
            else:
                ns.has_file = False
                
            
            ns.title = request.POST['title']
            ns.date = request.POST['date']  
            ns.body = request.POST['detail']
            ns.month = request.POST['month']
            ns.year = request.POST['year']
            ns.save()
            return redirect('news:news')
        else:
            return render(request, 'news/create.html',{'error_message':'All fields are required.'})
    else:
        return render(request,'news/create.html')


def detail(request,pk_id):
    ns = get_object_or_404(news,id = pk_id)
    return render(request,'news/detail.html',{'ns':ns})


@login_required(login_url = "/account")
def addupdate(request):
    if request.method == 'POST':
        
        
        if request.POST['title'] and request.POST['detail'] and request.POST['date'] and request.POST['month'] and  request.POST['year']:
            ns = update()
            if request.POST['gridRadios1'] == "1" and request.POST['url']:
                ns.url = request.POST['url']
                ns.has_url = True
            elif request.POST['gridRadios1'] == "1":
                return render(request, 'news/create.html',{'error_message':'Url required. or Change Has Url Option'})
            else:
                ns.has_url = False

            if request.POST['gridRadios'] == "1":
                try:
                    fm = request.FILES['fl']
                except MultiValueDictKeyError:
                    return render(request, 'news/create.html',{'error_message':'File required. or Change Has File Option'})
                ns.file = request.FILES['fl']
                ns.has_file = True
            else:
                ns.has_file = False
            
            if request.POST['gridRadios3'] == "1":
                try:
                    fm1 = request.FILES['img']
                except MultiValueDictKeyError:
                    return render(request, 'news/create_update.html',{'error_message':'Image required. or Change Has Image Option'})
                ns.image = request.FILES['img']
                ns.has_image = True
            else:
                ns.has_image = False
            
                
            
            ns.title = request.POST['title']
            ns.date = request.POST['date']  
            ns.body = request.POST['detail']
            ns.month = request.POST['month']
            ns.year = request.POST['year']
            ns.save()
            return redirect('news:news')
        else:
            return render(request, 'news/create_update.html',{'error_message':'All fields are required.'})
    else:
        return render(request,'news/create_update.html')

dupc/news/templates/news/news.html
{% extends 'base.html' %}

{% block ccd %}

  
<div id="marine-content-inner"> 
      <div class="page-heading"><br><br>
          <h2 style="color: #169EB7; font-weight: 400;align:center;">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Updates About the Project</h2>
        </div>
  <section id="main-content"> 
      <br><br>
    <div class="container">
        <br>
        <div class="row justify-content-end" style="font-size: 100%;font-weight:bold; font-family: Raleway;">
          <div class = "col-10">
          
              {%for update in up.all%}
              <div class = "container">
                <h5 style="color: #169EB7; font-weight: bold;font-family: Raleway;">{{update.title}}</h5>
                {%if update.has_image == True%}
                  <img src="{{update.image.url}}" class="img-fluid" alt="Responsive image" style = "">
                {%endif%}
                    <p style = "font-size: 100%;font-family: Raleway;">{{update.month}}&nbsp;{{update.date}},{{update.year}}.<br><br>{{update.body}}&nbsp;{%if update.has_url == True %}<a href = "{{update.url}}" style  = "color:#169EB7; text-decoration: none;"><span style="color: #169EB7; font-weight: bold;"><b> Know More</b></span></a>{%endif%}<br>{%if update.has_file == True%}<a href = "{{update.file.url}}" style  = "color:#169EB7; text-decoration: none;"><span style="color: #169EB7; font-weight: bold;"><b> Download/Read More</b></span></a>{%endif%}</p>
                    <br><br>
                    </div><br>
              {%endfor%}          
          
          </div>

            <div class="col-2">
              
              	<p style="color: #000; border-left: 2px solid #169EB7; padding-left: 15px;">
                
                <a href="{%url 'news:nss' 2020 'August'%}" style="color: #000;">Aug 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'September'%}" style="color: #000;">Sept 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'October'%}" style="color: #000;">Oct 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'November'%}" style="color: #000;">Nov 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'December'%}" style="color: #000;">Dec 2020</a><br><br>
                <a href="{%url 'news:nss' 2021 'January'%}" style="color: #000;">Jan 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'Febuary'%}" style="color: #000;">Feb 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'March'%}" style="color: #000;">Mar 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'April'%}" style="color: #000;">Apr 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'May'%}" style="color: #000;">May 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'June'%}" style="color: #000;">Jun 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'July'%}" style="color: #000;">Jul 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'August'%}" style="color: #000;">Aug 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'September'%}" style="color: #000;">Sept 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'October'%}" style="color: #000;">Oct 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'November'%}" style="color: #000;">Nov 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'December'%}" style="color: #000;">Dec 2021</a><br><br>
                <a href="{%url 'news:nss' 2022 'January'%}" style="color: #000;">Jan 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'February'%}" style="color: #000;">Feb 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'March'%}" style="color: #000;">Mar 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'April'%}" style="color: #000;">Apr 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'May'%}" style="color: #000;">May 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'June'%}" style="color: #000;">Jun 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'July'%}" style="color: #000;">Jul 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'August'%}" style="color: #000;">Aug 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'September'%}" style="color: #000;">Sept 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'October'%}" style="color: #000;">Oct 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'November'%}" style="color: #000;">Nov 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'December'%}" style="color: #000;">Dec 2022</a><br><br>
                <a href="{%url 'news:nss' 2023 'January'%}" style="color: #000;">Jan 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'February'%}" style="color: #000;">Feb 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'March'%}" style="color: #000;">Mar 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'April'%}" style="color: #000;">Apr 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'May'%}" style="color: #000;">May 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'June'%}" style="color: #000;">Jun 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'July'%}" style="color: #000;">Jul 2023</a><br><br>
                {% if user.is_authenticated %}
                  <h4 class="breadcrumbs"><span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'news:add'%}" role="button">Add News</a></span></h4>
            {%endif%}<br>
            {% if user.is_authenticated %}
                  <h4 class="breadcrumbs"><span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'news:addupdate'%}" role="button">Add Update</a></span></h4>
            {%endif%}<br>
              	</p>
            	</div>
          </div>
    </div>  
    </section>
 </div>
            	
<br>
{%endblock%}

<!-- /Marine Content Wrapper --> 

<!-- JavaScript --> 

<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/SmoothScroll.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.prettyPhoto.js"></script> 
<script type="text/javascript" src="assets/js/modernizr.js"></script> 
<script type="text/javascript" src="assets/js/wow.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.sharre.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.flexslider-min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.knob.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script> 
<script type="text/javascript" src="assets/js/masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.fitvids.js"></script> 
<script type="text/javascript" src="assets/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.nouislider.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.validity.min.js"></script> 
<script type="text/javascript" src="assets/js/tweetie.min.js"></script> 
<script type="text/javascript" src="assets/js/script.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.enablelog.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.tools.min.js"></script> 
<script type="text/javascript">



jQuery(document).ready(function() {



    jQuery('.tp-banner').show().revolution(



    {



        dottedOverlay:"none",



        delay:16000,



        startwidth:1170,



        startheight:700,



        hideThumbs:200,



        thumbWidth:100,



        thumbHeight:50,



        thumbAmount:5,



        navigationType:"bullet",



        navigationArrows:"solo",



        navigationStyle:"preview2",



        touchenabled:"on",



        onHoverStop:"on",



        swipe_velocity: 0.7,



        swipe_min_touches: 1,



        swipe_max_touches: 1,



        drag_block_vertical: false,



                                parallax:"mouse",



        parallaxBgFreeze:"on",



        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],



        keyboardNavigation:"off",



        navigationHAlign:"center",



        navigationVAlign:"bottom",



        navigationHOffset:0,



        navigationVOffset:20,



        soloArrowLeftHalign:"left",



        soloArrowLeftValign:"center",



        soloArrowLeftHOffset:20,



        soloArrowLeftVOffset:0,



        soloArrowRightHalign:"right",



        soloArrowRightValign:"center",



        soloArrowRightHOffset:20,



        soloArrowRightVOffset:0,



        shadow:0,



        fullWidth:"on",



        fullScreen:"off",



        spinner:"spinner4",



        stopLoop:"off",



        stopAfterLoops:-1,



        stopAtSlide:-1,



        shuffle:"off",



        autoHeight:"off",                       



        forceFullWidth:"off",                       



        hideThumbsOnMobile:"off",



        hideNavDelayOnMobile:1500,                      



        hideBulletsOnMobile:"off",



        hideArrowsOnMobile:"off",



        hideThumbsUnderResolution:0,



        hideSliderAtLimit:0,



        hideCaptionAtLimit:0,



        hideAllCaptionAtLilmit:0,



        startWithSlide:0,



        videoJsPath:"rs-plugin/videojs/",



        fullScreenOffsetContainer: ""   



    });



}); //ready



</script> 



<script src="assets/js/readmore.js"></script>

<script>
$('#info').readmore({
  moreLink: '<a href="#">Usage, examples, and options</a>',
  collapsedHeight: 384,
  afterToggle: function(trigger, element, expanded) {
    if(! expanded) { // The "Close" link was clicked
      $('html, body').animate({scrollTop: element.offset().top}, {duration: 100});
    }
  }
});

$('article').readmore({speed: 500});
</script>

<!-- Mirrored from marine.arenaofthemes.com/index-creative-light.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2015 21:07:18 GMT -->

dupc/news/templates/news/news_display.html
{% extends 'base.html' %}

{% block ccd %}

  
<div id="marine-content-inner"> 
  <section id="main-content"> 
    <div class="container">
        <br>
        <div class="row justify-content-end" style="font-size: 100%;font-weight:bold; font-family: Raleway;">
            <div class="col-lg-9 col-md-8 col-sm-9">
                <br><br>
                <div class = "row">
                {%for news in News.all%}
                    <div class="col-5" style = "">
                    <h5 style="color: #169EB7; font-weight: bold;font-family: Raleway;">{{news.title}}</h5>
                    <p style = "font-size: 100%;font-family: Raleway;">{{news.month}}&nbsp;{{news.date}},{{news.year}}.<br><br>{{news.summary}}&nbsp;<a href = "{%url 'news:detail' news.id %}" style  = "color:#169EB7; text-decoration: none;"><span style="color: #169EB7; font-weight: bold;"><b>Read More</b></span></a></p>
                    <br><br>
                    </div>
                    
                
                {%endfor%}
                </div>
            
            </div>
    
            <div class="col-lg-3 col-md-3 col-sm-3">
              	<p style="color: #000; border-left: 2px solid #169EB7; padding-left: 15px;">
                <a href="{%url 'news:nss' 2020 'August'%}" style="color: #000;">Aug 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'September'%}" style="color: #000;">Sept 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'October'%}" style="color: #000;">Oct 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'November'%}" style="color: #000;">Nov 2020</a><br><br>
                <a href="{%url 'news:nss' 2020 'December'%}" style="color: #000;">Dec 2020</a><br><br>
                <a href="{%url 'news:nss' 2021 'January'%}" style="color: #000;">Jan 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'Febuary'%}" style="color: #000;">Feb 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'March'%}" style="color: #000;">Mar 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'April'%}" style="color: #000;">Apr 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'May'%}" style="color: #000;">May 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'June'%}" style="color: #000;">Jun 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'July'%}" style="color: #000;">Jul 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'August'%}" style="color: #000;">Aug 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'September'%}" style="color: #000;">Sept 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'October'%}" style="color: #000;">Oct 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'November'%}" style="color: #000;">Nov 2021</a><br><br>
                <a href="{%url 'news:nss' 2021 'December'%}" style="color: #000;">Dec 2021</a><br><br>
                <a href="{%url 'news:nss' 2022 'January'%}" style="color: #000;">Jan 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'February'%}" style="color: #000;">Feb 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'March'%}" style="color: #000;">Mar 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'April'%}" style="color: #000;">Apr 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'May'%}" style="color: #000;">May 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'June'%}" style="color: #000;">Jun 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'July'%}" style="color: #000;">Jul 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'August'%}" style="color: #000;">Aug 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'September'%}" style="color: #000;">Sept 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'October'%}" style="color: #000;">Oct 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'November'%}" style="color: #000;">Nov 2022</a><br><br>
                <a href="{%url 'news:nss' 2022 'December'%}" style="color: #000;">Dec 2022</a><br><br>
                <a href="{%url 'news:nss' 2023 'January'%}" style="color: #000;">Jan 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'February'%}" style="color: #000;">Feb 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'March'%}" style="color: #000;">Mar 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'April'%}" style="color: #000;">Apr 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'May'%}" style="color: #000;">May 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'June'%}" style="color: #000;">Jun 2023</a><br><br>
                <a href="{%url 'news:nss' 2023 'July'%}" style="color: #000;">Jul 2023</a><br><br>

              	</p>
            	</div>

                
          </div>
    </div>  
    </section>
 </div>
            	
<br>
{%endblock%}

<!-- /Marine Content Wrapper --> 

<!-- JavaScript --> 

<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/SmoothScroll.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.prettyPhoto.js"></script> 
<script type="text/javascript" src="assets/js/modernizr.js"></script> 
<script type="text/javascript" src="assets/js/wow.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.sharre.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.flexslider-min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.knob.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script> 
<script type="text/javascript" src="assets/js/masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.fitvids.js"></script> 
<script type="text/javascript" src="assets/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.nouislider.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.validity.min.js"></script> 
<script type="text/javascript" src="assets/js/tweetie.min.js"></script> 
<script type="text/javascript" src="assets/js/script.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.enablelog.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.tools.min.js"></script> 
<script type="text/javascript">



jQuery(document).ready(function() {



    jQuery('.tp-banner').show().revolution(



    {



        dottedOverlay:"none",



        delay:16000,



        startwidth:1170,



        startheight:700,



        hideThumbs:200,



        thumbWidth:100,



        thumbHeight:50,



        thumbAmount:5,



        navigationType:"bullet",



        navigationArrows:"solo",



        navigationStyle:"preview2",



        touchenabled:"on",



        onHoverStop:"on",



        swipe_velocity: 0.7,



        swipe_min_touches: 1,



        swipe_max_touches: 1,



        drag_block_vertical: false,



                                parallax:"mouse",



        parallaxBgFreeze:"on",



        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],



        keyboardNavigation:"off",



        navigationHAlign:"center",



        navigationVAlign:"bottom",



        navigationHOffset:0,



        navigationVOffset:20,



        soloArrowLeftHalign:"left",



        soloArrowLeftValign:"center",



        soloArrowLeftHOffset:20,



        soloArrowLeftVOffset:0,



        soloArrowRightHalign:"right",



        soloArrowRightValign:"center",



        soloArrowRightHOffset:20,



        soloArrowRightVOffset:0,



        shadow:0,



        fullWidth:"on",



        fullScreen:"off",



        spinner:"spinner4",



        stopLoop:"off",



        stopAfterLoops:-1,



        stopAtSlide:-1,



        shuffle:"off",



        autoHeight:"off",                       



        forceFullWidth:"off",                       



        hideThumbsOnMobile:"off",



        hideNavDelayOnMobile:1500,                      



        hideBulletsOnMobile:"off",



        hideArrowsOnMobile:"off",



        hideThumbsUnderResolution:0,



        hideSliderAtLimit:0,



        hideCaptionAtLimit:0,



        hideAllCaptionAtLilmit:0,



        startWithSlide:0,



        videoJsPath:"rs-plugin/videojs/",



        fullScreenOffsetContainer: ""   



    });



}); //ready



</script> 



<script src="assets/js/readmore.js"></script>

<script>
$('#info').readmore({
  moreLink: '<a href="#">Usage, examples, and options</a>',
  collapsedHeight: 384,
  afterToggle: function(trigger, element, expanded) {
    if(! expanded) { // The "Close" link was clicked
      $('html, body').animate({scrollTop: element.offset().top}, {duration: 100});
    }
  }
});

$('article').readmore({speed: 500});
</script>

<!-- Mirrored from marine.arenaofthemes.com/index-creative-light.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2015 21:07:18 GMT -->