dupc/dupc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainsite.urls',namespace='mainsite')),
    path('account/',include('account.urls',namespace='account')),
    
    path('publication/',include('publication.urls',namespace='publication')),
    path('news_and_updates/',include('news.urls',namespace = 'news')),
    path('outreach/',include('outreach.urls',namespace = 'outreach')),
    path('reports/',include('reports.urls',namespace='reports')),
    path('stories/',include('stories.urls',namespace='stories')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/accounts/login/',views.loginn,name = 'login')
]+  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

dupc/mainsite/urls.py
from django.conf.urls import url, include
from .import views
from django.contrib import admin
from django.urls import path
app_name = 'mainsite'
urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('teams/',views.teams,name ='teams'),
    path('teams/<int:pk_id>/',views.detail,name = 'detail'),
    path('add/',views.add,name = 'add'),
    path('account/',include('account.urls',namespace='account')),
    path('aim/',views.aim,name = 'aim'),
    path('background/',views.background, name = 'background'),
    path('activities/',views.activity,name = 'activity'),
    path('teams/anamika/' ,views.anamika,name  = 'anamika'),
    path('teams/<int:pk_id>/remove/',views.remove,name = 'remove'),
    path('contact/',views.contact,name = 'contact'),
]

dupc/mainsite/models.py
from __future__ import unicode_literals

from django.db import models

class team(models.Model):
    name = models.CharField(max_length = 100)
    image = models.ImageField(upload_to = 'images/', default = 'download.png')
    designation = models.CharField(max_length = 1500, default= None)
    institute_name = models.CharField(max_length = 1500,default = 'IITG',blank=True)
    department = models.CharField(max_length=1500,default = 'HSS',blank=True)
    information = models.TextField(max_length = 3000, default= None)
    
    def __str__(self):
        return self.name

    def ida(self):
        return self.name[:2]
    

dupc/mainsite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .models import team
from django.utils.datastructures import MultiValueDictKeyError
from news.models import update
from publication.models import publication
from outreach.models import podcast

# Create your views here.


def homepage(request):
    up = update.objects.filter().order_by('-id')[:3]
    pb = publication.objects.filter().order_by('-id')[:3]
    pod = podcast.objects.filter().order_by('-id')[:3]

    return render(request,'index1.html',{'up':up,'pb':pb,'pod':pod })



def teams(request):    
    tm = team.objects
    return render(request,'teams.html',{'tm':tm})

@login_required(login_url = "/account")
def add(request):
    if request.method == 'POST':
        
        
        if request.POST['name'] and request.POST['designation'] and request.POST['body'] and request.POST['institute_name'] and request.POST['department']:
            try:
                fm = request.FILES['img']
            except MultiValueDictKeyError:
                return render(request, 'addteam.html',{'error_message':'All fields are required.'})
                
            tm = team()
            tm.name = request.POST['name']
            tm.designation = request.POST['designation']
            tm.information = request.POST['body']
            tm.image = request.FILES['img']
            tm.institute_name = request.POST['institute_name']
            tm.department = request.POST['department']
            tm.save()
            return redirect('mainsite:teams')
        else:
            return render(request, 'addteam.html',{'error_message':'All fields are required.'})
    else:
        return render(request,'addteam.html')

def background(request):
    return render(request,'background1.html')



def aim(request):
    return render(request,'aim.html')


def activity(request):
    return render(request,'activity.html')


def detail(request,pk_id):
    member = get_object_or_404(team,pk = pk_id)
    return render(request,'detail.html',{'member': member}) 

def anamika(request):
    return render(request,'detail_anamika.html')
    

@login_required(login_url = "/account")
def remove(request,pk_id):
    member = get_object_or_404(team,pk = pk_id)
    member.delete()
    return redirect('mainsite:teams')


def contact(request):
    return render(request,'contact.html')

dupc/mainsite/templates/activity.html
{% extends 'base.html' %}

{% block ccd %}

  
<div id="marine-content-inner"> 
    
    <!-- Main Content -->
    
    <section id="main-content"> 
      
      <!-- Container -->
      <br><br>
      <div class="container">
          <div class="row justify-content-start" style="font-size: 120%; font-family: Raleway;">
            <div class="col-lg-3 col-md-3 col-sm-3">
              <p style="color: #000; border-left: 2px solid #169EB7; padding-left: 15px;">
                <a href="{%url 'mainsite:background' %}" style="color: #000;">Background</a><br><br>
                <a href="{%url 'mainsite:activity'%}" style="color: #000;">Activities</a><br><br>
                <a href="{%url 'mainsite:teams'%}" style="color: #000;">Team</a>
              </p>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7">
              <div class="page-heading">
                <h2 style="color: #169EB7; font-weight: 400;">ACTIVITIES</h2>
              </div>
              <br>
                <p>
                    <strong style="color: #169EB7;"> Activity 1: Scoping research: </strong><br>
                    To conduct an in-depth study on the role of the media in water conflicts and cooperation in the Brahmaputra. The scoping research will try to understand media and science’s historical and current engagement: How do they work? Where do they find relevant experts? Where do they get their data and figures from? What are the implications of specific framing for water conflicts and cooperation? Does the current political situation influence the media's reporting?
                    <br><br>
                    It is usually not possible for them to atend workshops with continuation or at length. The inclusion and capacity building of the editors is significant as no matter how hard the journalist works for a report/story; unless it recieves approval from the editors it is a futile exercise.
                </p>
                <br><br>
                <p>
                    <strong style="color: #169EB7;">Activity 2: Communication strategy for scientists and media:</strong><br>
                    It will focus on improving communication skills of the scientific community and media through:<br><br>
                    <strong style="color: #169EB7;">Online course:</strong><br>
                    The aim of the online course will be to enable the scientists to communicate their work in a manner that is easily understood and disseminated by the media. The project will improve and retune an already existing course that at the moment is tailored for the Nile basin, to scale it up as a general course on communication skills for water diplomacy.
                    <br><br>
                    <strong style="color: #169EB7;">Webinar:</strong><br>
                    For the editors and journalists of the media outlets will be organized as it is usually not possible for them to attend workshops with continuation or at length. The inclusion and capacity building of the editors is significant as no matter how hard the journalist works for a report/story; unless it receives approval from the editors it is a futile exercise.
                </p>
                <br><br>
                <p>
                    <strong style="color: #169EB7;">Activity 3: Knowledge production:</strong><br>
                    Thematic workshop, focusing on aspects like disaster risk management, hydrogeology of the Brahmaputra River, socio-economic dependency on the river, gender and water diplomacy etc., will be conducted to build the capacity of media personnel. To sustain the process of science and media diplomacy for water, connecting the scientific community and media will be vital.
                    <br><br>
                    A roster of the scientific community, dividing them on the basis of their expertise will also be generated. While the multimedia stories/video grants would assist in bringing together researchers and media personnel with communities who live in the basin and are dependent on the natural resources of the basin for their livelihoods. A photography competition / exhibition will also be organized either online or during the thematic workshop.
                </p>
                <br><br>
                <p>
                    <strong style="color: #169EB7;">Activity 4: Outreach:</strong><br>
                    Social Media Campaign: In the 21st century, social media campaign is integral as an outreach mechanism for dissemination of information. On twitter, facebook and instagram, hashtags such as #EverydayBrahmaputra would be initiated for posting regular updates.
                    <br><br>
                    Podcasts will bring diverse stories from the basin, depicting the local communities’ association with the river from different aspects like social, cultural, economic, spiritual, religious, etc.
                </p>
            </div>
          </div>
        </div>
      
      

     
      
    </section>

    
    <!-- /Main Content -->
    
    <section id="main-content"> </section>
  </div>
  
  <!-- /Marine Conten Inner --> 
  
  <!-- Lower Footer -->
  
  
  
  <!-- /Lower Footer --> 
  
</div>
<br>
{%endblock%}

<!-- /Marine Content Wrapper --> 

<!-- JavaScript --> 

<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/SmoothScroll.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.prettyPhoto.js"></script> 
<script type="text/javascript" src="assets/js/modernizr.js"></script> 
<script type="text/javascript" src="assets/js/wow.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.sharre.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.flexslider-min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.knob.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script> 
<script type="text/javascript" src="assets/js/masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.fitvids.js"></script> 
<script type="text/javascript" src="assets/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.nouislider.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.validity.min.js"></script> 
<script type="text/javascript" src="assets/js/tweetie.min.js"></script> 
<script type="text/javascript" src="assets/js/script.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.enablelog.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.tools.min.js"></script> 
<script type="text/javascript">



jQuery(document).ready(function() {



    jQuery('.tp-banner').show().revolution(



    {



        dottedOverlay:"none",



        delay:16000,



        startwidth:1170,



        startheight:700,



        hideThumbs:200,



        thumbWidth:100,



        thumbHeight:50,



        thumbAmount:5,



        navigationType:"bullet",



        navigationArrows:"solo",



        navigationStyle:"preview2",



        touchenabled:"on",



        onHoverStop:"on",



        swipe_velocity: 0.7,



        swipe_min_touches: 1,



        swipe_max_touches: 1,



        drag_block_vertical: false,



                                parallax:"mouse",



        parallaxBgFreeze:"on",



        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],



        keyboardNavigation:"off",



        navigationHAlign:"center",



        navigationVAlign:"bottom",



        navigationHOffset:0,



        navigationVOffset:20,



        soloArrowLeftHalign:"left",



        soloArrowLeftValign:"center",



        soloArrowLeftHOffset:20,



        soloArrowLeftVOffset:0,



        soloArrowRightHalign:"right",



        soloArrowRightValign:"center",



        soloArrowRightHOffset:20,



        soloArrowRightVOffset:0,



        shadow:0,



        fullWidth:"on",



        fullScreen:"off",



        spinner:"spinner4",



        stopLoop:"off",



        stopAfterLoops:-1,



        stopAtSlide:-1,



        shuffle:"off",



        autoHeight:"off",                       



        forceFullWidth:"off",                       



        hideThumbsOnMobile:"off",



        hideNavDelayOnMobile:1500,                      



        hideBulletsOnMobile:"off",



        hideArrowsOnMobile:"off",



        hideThumbsUnderResolution:0,



        hideSliderAtLimit:0,



        hideCaptionAtLimit:0,



        hideAllCaptionAtLilmit:0,



        startWithSlide:0,



        videoJsPath:"rs-plugin/videojs/",



        fullScreenOffsetContainer: ""   



    });



}); //ready



</script> 



<script src="assets/js/readmore.js"></script>

<script>
$('#info').readmore({
  moreLink: '<a href="#">Usage, examples, and options</a>',
  collapsedHeight: 384,
  afterToggle: function(trigger, element, expanded) {
    if(! expanded) { // The "Close" link was clicked
      $('html, body').animate({scrollTop: element.offset().top}, {duration: 100});
    }
  }
});

$('article').readmore({speed: 500});
</script>

<!-- Mirrored from marine.arenaofthemes.com/index-creative-light.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2015 21:07:18 GMT -->

dupc/mainsite/templates/addteam.html
{% extends 'base.html' %}
 {% block ccd %}
    <br>
    <b><h3 style="padding-left: 13%;">Add Team Member Credentials</h3></b>
    <div class = "container" >
    <br>
    {% if error_message %}
      
<div class="alert alert-danger" >
  <strong>Warning!</strong> {{error_message}}
</div>
    {% endif %}
    </div>

    <form action = "#", method = 'POST' enctype = "multipart/form-data" >
     {% csrf_token %}
  <div class="form-group" style="margin-left: 12%;">
        <div class="col-3">
            Name:
            <input type="text" class="form-control" name ="name" aria-describedby="text" placeholder="Enter member name">
        </div>
  </div>
  <div class="form-group" style="margin-left: 12%;">
        <div class="col-3">
            Designation
            <input type="text" class="form-control" name ="designation" aria-describedby="text" placeholder="Enter Member Designation">
        </div>
  </div>
  <div class="form-group" style="margin-left: 12%;">
        <div class="col-3">
            Department
            <input type="text" class="form-control" name ="department" aria-describedby="text" placeholder="Enter Department">
        </div>
  </div>
  <div class="form-group" style="margin-left: 12%;">
        <div class="col-3">
            Institute Name
            <input type="text" class="form-control" name ="institute_name" aria-describedby="text" placeholder="Institute Name">
        </div>
  </div>
   <div class="form-group"style="margin-left: 12%;">
    <div class="col-3">
    Details:
    <textarea class="form-control" name = "body" rows="4" placeholder ="Enter member details"></textarea>
    </div>
  </div>

    <div class="form-group"style="margin-left: 12%;">
        <div class="col-3">
      Upload Image:
    <input type = "file" class = "form-control-file" name = "img">
    </div>
  </div>
  <div align  = "center" >
  <button type="submit" class="btn btn-success">Add Team Member</button>
  </div>
  </form>

 
 <br>
{% endblock %}

dupc/mainsite/templates/detail.html
{% extends 'base.html' %}

{% block ccd %}
        <div id="marine-content-inner"> 
      <div class="container">
        
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <br>
              <h3 style="color:black" align = "center">Meet our Team</h3>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
               <br>
                {% if user.is_authenticated %}
              <h4 class="breadcrumbs" align = "right"> <span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'mainsite:add'%}" role="button">Add Member</a></span></h4>
                {%endif%}
            </div>
          </div>
        
        
</div>
<hr>

    <div class = "container">
    <p><img class=" img-fluid" height = "250px" width = "250px" src="{{member.image.url}}" alt="card image"></p>
        <h4> {{member.name}} </h4>
        <p> {{member.email_id}}</p>
        <p>{{member.phone}}</p>
        </p>{{member.information}}</p>
    </div>

{% endblock %}

dupc/mainsite/templates/detail_anamika.html
{% extends 'base.html' %}

{% block ccd %}
        <div id="marine-content-inner"> 
      <div class="container">
        
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <br>
              <h3 style="color:black" align = "center">Meet our Team</h3>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
               <br>
                {% if user.is_authenticated %}
              <h4 class="breadcrumbs" align = "right"> <span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'mainsite:add'%}" role="button">Add Member</a></span></h4>
                {%endif%}
            </div>
          </div>
        
        
</div>
<hr>

    <div class = "container">
    <p><img class=" img-fluid" height = "250px" width = "250px" src = "/static/images/anamika.JPG" alt="card image"></p>
        <h4>Anamika Barua </h4>
        <a href = https://www.linkedin.com/in/anamika-barua-95a55065 class="btn btn-primary"> Linkedin</a> 
        </p>Dr. Anamika Barua is an Associate professor in the Dept. of Humanities and Social Sciences, Indian Institute of Technology Guwahati (IITG), India. Trained in Ecological Economics, her research interest lies in understanding how political, social and economic factors shape environmental decisions and change, particularly related to water. For the last ten years, she has been involved in academic and consultancy project related to water issues in South Asia. Her research interest includes – climate change and water security, ecological footprints, virtual water flow through trade and water governance including transboundary water governance. She is at present facilitating a dialogue project called Brahmaputra Dialogue, which aims to create a platform for the Brahmaputra riparian countries to find avenues for co-management of the River.  </p>
        
        
      
    </div>

{% endblock %}

dupc/mainsite/templates/teams.html
{% extends 'base.html' %}

{% block ccd %}
{% load static %}
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div id="marine-content-inner"> 
  <br><br>
      <div class="container">
          <div class="row justify-content-start" style="font-size: 120%; font-family: Raleway;">
            <div class="col-lg-3 col-md-3 col-sm-3">
              <p style="color: #000; border-left: 2px solid #169EB7; padding-left: 15px;">
                <a href="{%url 'mainsite:background' %}" style="color: #000; " >Background</a><br><br>
                <a href="{%url 'mainsite:activity'%}" style="color: #000;">Activities</a><br><br>
                <a href="{%url 'mainsite:teams'%}" style="color: #000;">Team</a>
              </p>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7">
              <div class="page-heading">
                <h2 style="color: #169EB7; font-weight: 400;">TEAM</h2>
              </div>
              <br>
                             
                {% for member in tm.all %}
                <div>
                
                  <img class=" img-fluid" src="{{member.image.url}}" width = "30%" height = "40%" style="top: 0; vertical-align: top;">
                  <p style="display: inline-block; font-size: 90%; padding-top: 5px; font-weight: bold; padding-left: 10px;">

                  <b style="color: #169EB7; margin-top: 20px;">{{member.name}}</b><br>
                  {{ member.designation }}<br>
                  {{ member.department }}<br>
                  {{ member.institute_name }}<br>
                  <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#{{member.ida}}" aria-expanded="false"  style="background-color: #FFF; color: #169EB7;">Know More&nbsp;<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-down-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg></button>
                  <br><br>
                  
                </p>
                <br><br>
                <div class="collapse" id="{{member.ida}}" style="border: 1.2px solid #169EB7; border-radius: 5px;">
                  <div class="card card-body">
                    {{member.information}}    
                  </div>
                </div>
                
              </div>
                <br><br><br>
                {% endfor %}
            </div>
          </div>
        </div>


      <div class="container">
        
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
          <br>
            {% if user.is_authenticated %}
          <h4 class="breadcrumbs" align = "right"><span typeof="v:Breadcrumb"><a class="btn btn-dark" href="{%url 'mainsite:add'%}" role="button">Add Member</a></span></h4>
            {%endif%}
        </div>
      </div>
        
        
</div>
<br>
{%endblock%}

<!-- /Marine Content Wrapper --> 

<!-- JavaScript --> 

<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/SmoothScroll.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.prettyPhoto.js"></script> 
<script type="text/javascript" src="assets/js/modernizr.js"></script> 
<script type="text/javascript" src="assets/js/wow.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.sharre.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.flexslider-min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.knob.js"></script> 
<script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script> 
<script type="text/javascript" src="assets/js/masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.masonry.min0226.js"></script> 
<script type="text/javascript" src="assets/js/jquery.fitvids.js"></script> 
<script type="text/javascript" src="assets/js/perfect-scrollbar-0.4.10.with-mousewheel.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.nouislider.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.validity.min.js"></script> 
<script type="text/javascript" src="assets/js/tweetie.min.js"></script> 
<script type="text/javascript" src="assets/js/script.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.enablelog.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.revolution.min.js"></script> 
<script type="text/javascript" src="assets/js/jquery.themepunch.tools.min.js"></script> 
<script type="text/javascript">



jQuery(document).ready(function() {



    jQuery('.tp-banner').show().revolution(



    {



        dottedOverlay:"none",



        delay:16000,



        startwidth:1170,



        startheight:700,



        hideThumbs:200,



        thumbWidth:100,



        thumbHeight:50,



        thumbAmount:5,



        navigationType:"bullet",



        navigationArrows:"solo",



        navigationStyle:"preview2",



        touchenabled:"on",



        onHoverStop:"on",



        swipe_velocity: 0.7,



        swipe_min_touches: 1,



        swipe_max_touches: 1,



        drag_block_vertical: false,



                                parallax:"mouse",



        parallaxBgFreeze:"on",



        parallaxLevels:[7,4,3,2,5,4,3,2,1,0],



        keyboardNavigation:"off",



        navigationHAlign:"center",



        navigationVAlign:"bottom",



        navigationHOffset:0,



        navigationVOffset:20,



        soloArrowLeftHalign:"left",



        soloArrowLeftValign:"center",



        soloArrowLeftHOffset:20,



        soloArrowLeftVOffset:0,



        soloArrowRightHalign:"right",



        soloArrowRightValign:"center",



        soloArrowRightHOffset:20,



        soloArrowRightVOffset:0,



        shadow:0,



        fullWidth:"on",



        fullScreen:"off",



        spinner:"spinner4",



        stopLoop:"off",



        stopAfterLoops:-1,



        stopAtSlide:-1,



        shuffle:"off",



        autoHeight:"off",                       



        forceFullWidth:"off",                       



        hideThumbsOnMobile:"off",



        hideNavDelayOnMobile:1500,                      



        hideBulletsOnMobile:"off",



        hideArrowsOnMobile:"off",



        hideThumbsUnderResolution:0,



        hideSliderAtLimit:0,



        hideCaptionAtLimit:0,



        hideAllCaptionAtLilmit:0,



        startWithSlide:0,



        videoJsPath:"rs-plugin/videojs/",



        fullScreenOffsetContainer: ""   



    });



}); //ready



</script> 



<script src="assets/js/readmore.js"></script>

<script>
$('#info').readmore({
  moreLink: '<a href="#">Usage, examples, and options</a>',
  collapsedHeight: 384,
  afterToggle: function(trigger, element, expanded) {
  if(! expanded) { // The "Close" link was clicked
    $('html, body').animate({scrollTop: element.offset().top}, {duration: 100});
  }
  }
});

$('article').readmore({speed: 500});
</script>

<!-- Mirrored from marine.arenaofthemes.com/index-creative-light.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 11 May 2015 21:07:18 GMT -->